name: my caller work flow

on:
  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT'
        required: false
        type: boolean
      user-name:
        description: 'user name to called work flow'
        required: true
        type: string      
        
jobs:

  print-logs:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }}
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: check the python version
        run: python --version

      - name: print git hub workspace
        run: echo $GITHUB_WORKSPACE

      - name: pring the input tag to STDOUT
        run: echo the tags are ${{ inputs.print_tags}}

  calling-resuable-work-flow:
    uses: ./.github/workflows/my_called_work_flow.yml@master
    with:
      user-name: ${{ inputs.user-name }}

  calling-resuabl-work-flow-another-repo:
    uses: rayinianji/practice_git_hubactions/.github/workflows/my_called_work_flow.yml@master
    with:
      user-name: ${{ inputs.user-name }} 


    




