name: my called work flow

on:
  workflow_call:
    inputs:  
      user-name:
        description: 'A user name passed from the caller workflow'
        default: 'Anjaneyulu-rayini'
        required: false
        type: string
  
jobs:
  print-username:
    runs-on: ubuntu-latest
    
    steps:
      - name: print the input name to STDOUT
        run: echo ${{inputs.user-name}}
        